config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "movies#new_import"
  resources :actors, only: [:index, :show] do
    collection do
      get :search
    end
  end
  resources :movies, only: [:index] do
    collection do
      get :new_import
      post :perform_import
    end
  end
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :actors_movies, dependent: :destroy
  has_many :movies, through: :actors_movies
end

app/models/actors_movie.rb
class ActorsMovie < ApplicationRecord
  belongs_to :actor
  belongs_to :movie
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :actors_movies, dependent: :destroy
  has_many :actors, through: :actors_movies
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def index
    @actors = Actor.all
  end

  def search
    query = params[:query]
    @actors = Actor.where("name ILIKE ?", "%#{query}%")
  end

  def show
    @actor = Actor.find(params[:id])
    @movies = @actor.movies
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagination
end

app/controllers/concerns/pagination.rb
module Pagination
  extend ActiveSupport::Concern

  def default_per_page
    25
  end

  def page_no
    params[:page]&.to_i || 1
  end

  def per_page
    params[:per_page]&.to_i || default_per_page
  end

  def paginate_offset
    (page_no-1)*per_page
  end

  def paginate
    ->(it){ it.limit(per_page).offset(paginate_offset) }
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.order(average_rating: :desc)
    @movies.then(&paginate)

  end

  def new_import; end

  def perform_import
    movies_csv = params[:movies_csv]
    reviews_csv = params[:reviews_csv]

    if movies_csv.present? && reviews_csv.present?
      Services::ImportData.import_data(movies_csv.path, reviews_csv.path)
      flash[:notice] = 'CSV import completed successfully.'
    else
      flash[:error] = 'Please select both movies and reviews CSV files to import.'
    end

    redirect_to movies_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/actors/_actors_list.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.name %></td>
        <td><%= link_to 'View Movies', actor_path(actor) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/actors/index.html.erb
<h1>All Actors</h1>

<%= form_tag(search_actors_path, method: :get) do %>
  <%= text_field_tag :query %>
  <%= submit_tag "Search Actor" %>
<% end %>

<%= render partial: 'actors_list', locals: { actors: @actors } %>

app/views/actors/show.html.erb
<h1><%= @actor.name %></h1>

<h2>Movies:</h2>
<% if @movies.any? %>
  <ul>
    <% @movies.each do |movie| %>
      <li><%= movie.title %></li>
    <% end %>
  </ul>
<% else %>
  <p>No movies found for this actor.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoviesAssignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_movies_list.html.erb
<td><%= movie.title %></td>
<td><%= movie.average_rating %></td>

app/views/movies/index.html.erb
<h1>All Movies</h1>
<% if @movies.present? %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Average Rating</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>

       <tr> <%= render partial: 'movies_list', locals: { movie: movie } %></tr>
    <% end %>
      </tbody>
</table>

<% else %>
  <p>No movies found.</p>
<% end %>

<td><%= link_to 'View Actors', actors_path %></td>

app/views/movies/new_import.html.erb
<h1>Data Import</h1>

<%= form_tag(perform_import_movies_path, multipart: true) do %>
  <div>
    <label for="movies_csv">Movies CSV:</label>
    <%= file_field_tag :movies_csv %>
  </div>

  <div>
    <label for="reviews_csv">Reviews CSV:</label>
    <%= file_field_tag :reviews_csv %>
  </div>

  <%= submit_tag 'Import' %>
<% end %>